---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ((docker-repo-name))/cpi-release-build-env
    tag: "latest"
inputs:
  - name: src-develop
  - name: final-version-semver
outputs:
  - name: promoted
run:
  path: src-develop/ci/tasks/promote-to-master.sh
